"""added attendance breakdown

Revision ID: 33760fa71246
Revises: 3df0abad5d75
Create Date: 2026-05-26 09:45:03.173363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33760fa71246'
down_revision = '3df0abad5d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('men', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('women', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('youths', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('children', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('visitors', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('visitors')
        batch_op.drop_column('children')
        batch_op.drop_column('youths')
        batch_op.drop_column('women')
        batch_op.drop_column('men')

    # ### end Alembic commands ###
