"""Add baptism_status, address, join_date to members table

Revision ID: 4d50ffd385ad
Revises: 33760fa71246
Create Date: 2026-05-26 14:49:19.521082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d50ffd385ad'
down_revision = '33760fa71246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('baptism_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('join_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('join_date')
        batch_op.drop_column('baptism_status')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
