"""add member_id to council_members

Revision ID: 4e645f8e53b3
Revises: 4c4f47a4a71f
Create Date: 2026-06-21 21:04:55.875869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e645f8e53b3'
down_revision = '4c4f47a4a71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('council_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('council_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
