"""add sms_logs

Revision ID: 5169543ce72f
Revises: 4d50ffd385ad
Create Date: 2026-06-18 22:41:26.992730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5169543ce72f'
down_revision = '4d50ffd385ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_phone', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_recipient_phone'), ['recipient_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_status'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_recipient_phone'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_created_at'))

    op.drop_table('sms_logs')
    # ### end Alembic commands ###
