"""add pending_deletions

Revision ID: 71a81d3c2217
Revises: a91c5c76995c
Create Date: 2026-07-26 14:02:44.924621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71a81d3c2217'
down_revision = 'a91c5c76995c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_deletions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('record_label', sa.String(length=255), nullable=True),
    sa.Column('record_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('requested_by_email', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_deletions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_deletions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_deletions_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_deletions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_deletions_table_name'), ['table_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_deletions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_deletions_table_name'))
        batch_op.drop_index(batch_op.f('ix_pending_deletions_status'))
        batch_op.drop_index(batch_op.f('ix_pending_deletions_record_id'))
        batch_op.drop_index(batch_op.f('ix_pending_deletions_created_at'))

    op.drop_table('pending_deletions')
    # ### end Alembic commands ###
