"""add fellowship_schedules table

Revision ID: 8087d7ec7f9b
Revises: 4e645f8e53b3
Create Date: 2026-06-26 12:15:17.235910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8087d7ec7f9b'
down_revision = '4e645f8e53b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fellowship_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fellowship_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=False),
    sa.Column('programme', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fellowship_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fellowship_schedules_fellowship_date'), ['fellowship_date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fellowship_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fellowship_schedules_fellowship_date'))

    op.drop_table('fellowship_schedules')
    # ### end Alembic commands ###
