"""Updated Programme to Programmer

Revision ID: e774aac868d1
Revises: 8087d7ec7f9b
Create Date: 2026-06-26 12:34:10.081764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e774aac868d1'
down_revision = '8087d7ec7f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fellowship_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('programmer', sa.Text(), nullable=False))
        batch_op.drop_column('programme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fellowship_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('programme', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('programmer')

    # ### end Alembic commands ###
